version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - messageservicenetwork
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    ports:
      - '5601:5601'
    networks:
      - messageservicenetwork
    depends_on:
      - elasticsearch
  rabbitmq:
    image: rabbitmq:3.6.10
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '25672:25672'
    networks: 
      - messageservicenetwork
networks:
  messageservicenetwork:
    driver: bridge